
  CREATE TABLE "SYS"."DRIVER_DELIVERIES" 
   (	"DRIVER_DELIVERY_ID" NUMBER(38,0), 
	"VIN_NUMBER" VARCHAR2(26 BYTE), 
	"DRIVER_ID" NUMBER(38,0), 
	"DELIVERY_ITEM_ID" NUMBER(38,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

